[phases.setup]
nixPkgs = ['python39', 'gcc']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = ['python -m compileall .']

[start]
cmd = 'python bot.py'